### ISSUE TITLE
Support `layer.features`

### ISSUE THREAD

**Issue by haesleinhuepf** [fractal-napari-plugins-collection/napari-feature-classifier#12]
Hi @jluethi ,

that's fantastic plugin you just released! May I suggest a little feature? There is a couple of napari-plugins that do feature extraction and save these features into a label layer (`layer.properties` is a dictionary and `layer.features` is a pandas DataFrame): 

* [napari-skimage-regionprops](https://github.com/haesleinhuepf/napari-skimage-regionprops/)
* [napari-clusters-plotter](https://github.com/BiAPoL/napari-clusters-plotter/)
* [napari-simpleitk-image-processing](https://github.com/haesleinhuepf/napari-simpleitk-image-processing/)
* [napari-cupy-image-processing](https://github.com/haesleinhuepf/napari-cupy-image-processing/) 
* [napari-pyclesperanto-assistant](https://github.com/clEsperanto/napari_pyclesperanto_assistant/) 

If your plugin could read from those extracted features, users would not have to save and load a csv file.

Let me know if that makes sense and/or if I can assist in making it happen. :-)

Best,
Robert

**Comment by jluethi** [comment]
> Typically, the features dataframe contains a column label that is identical with the pixel intensity in the label image.

Sure, that is critical. I meant more in the sense of "is there an identifier for the whole label image that is stable". E.g. in my csv workflow, I have a `label` column, but also a second index column for `path` that saves the csv file path => relates the measurement to the specific image, not just the object within the image

> If you're interested on collaborating on this, I'm working on a very similar project: [apoc](https://github.com/haesleinhuepf/apoc) which can also [train pixel and object classifiers on folders of images](https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/20a_pixel_classification/apoc_train_on_folders.html). Apoc therefore includes feature extraction and I'm https://github.com/haesleinhuepf/apoc/issues/7 and for https://github.com/haesleinhuepf/apoc/issues/8. It looks to me we're working on very similar things ;-)

Fascinating! Haha, yeah, looks like we're somewhat converging once more! I was aware of the pixel classifier part you're doing, didn't actually realize it also does object classification! And sure, would be a great idea to collaborate and see whether my features & workflows can eventually end up in [apoc](https://github.com/haesleinhuepf/apoc) or whether two distinct plugins with separate use cases is the best way forward :) On a first look, seems like you're already very far with handling the direct processing of images, while my approach is more focused on dealing with existing label images and large amounts of (existing) measurements. Let's chat sometime about how to avoid doing duplicate work here :)
Thanks for the shout-out on your readme page btw! Will also link yours. Especially because my approach doesn't actually do any pixel classification and people may be looking for that when they think classifier :)

> You are also working with Random Forest Classifiers from Scikit-learn, right?

Yes! All Scikit-learn Random Forests behind it. Was considering adding different Scikit-learn classifiers as options, but didn't seem worth the trouble given how well the random forests perform :)

**Comment by haesleinhuepf** [comment]
> Was considering adding different Scikit-learn classifiers as options, but didn't seem worth the trouble given how well the random forests perform :)

Same here. 🙌

**Comment by andy-sweet** [comment]
> No `properties` is deprecated and future development should use `features`. Maybe @andy-sweet can tell us more.

Yes, that's about right. Though `properties` has not been officially deprecated yet (i.e. you won't get a `DeprecationWarning` when using it and its relatives until #3911 is done). That's not a great state to be in, but the set of changes is quite large and there are still some finishing touches needed to make `features` complete (e.g. #4079).

My recommendation would be to try to use `features`, and fall back to `properties` if you're missing some desired functionality (in which case tell me to implement that functionality ASAP!).

> layer.features is a pandas DataFrame

It's true that we're currently using pandas `DataFrame` as our implementing store of `features` (and `properties` too). But you shouldn't rely on that typing too strongly [as mentioned in the docstring](https://github.com/napari/napari/blob/e13f8651f8bd0151b5ef81f93b28035397576ec5/napari/layers/points/points.py#L545). Apologies for the lack of clarity, but you should think of it as something like a very minimal API that is shared between the common DataFrame libraries (e.g. pandas, vaex, dask, cuDF).

```python
class DataFrameLike(Protocol):
    shape: Tuple[int, ...]
    def __getitem__(self, key: str) -> ArrayLike:
        ...
    def __setitem__(self, key: str, value: ArrayLike) -> None:
        ...
```

Likely with support for `iloc` too to support integer indexing and arrays. We may specifically target the in-development DataAPIs protocol, but I think that's more about data interchange than API compatibility.

If you do need to rely specifically on a pandas `DataFrame` in the long term, you can use [`features_to_pandas_dataframe`](https://github.com/napari/napari/blob/e13f8651f8bd0151b5ef81f93b28035397576ec5/napari/layers/utils/layer_utils.py#L667), but in the future that may make copies of the underlying data.

> Being based on csv file on disk would keep the option open to load additional data later if I implement the feature for it.

One reason we don't want to commit to a particular package's DataFrame is to try to support these kinds of use cases. For example, you might be able to use a [vaex DataFrame](https://vaex.io/docs/index.html) to lazily load data. That won't currently work with napari because we do always convert to a pandas DataFrame right now, but that is something I would be very open to changing in the future. So if that sounds promising, let me know, and we may be able to get some momentum behind it.

**Comment by andy-sweet** [comment]
> 2\. To do this multi-site/multi-image approach, I need two layers of identifiers for my object: Their label and the corresponding image. When using csv files, I use the csv file path to handle this. Is there a unique identifier I could use for the label image when loading `layer.properties` or `layer.features`?

If I understand the goal here, the crudest approach would be to prepend some unique string to the column names of the features to identify each image. By the sounds of your work, that table is going to be very wide though.

I have been considering whether we want to store feature measurements outside of any particular layer, which may be a more general purpose solution. So if that sounds promising, please push on that too.

**Comment by jluethi** [comment]
>My recommendation would be to try to use features, and fall back to properties if you're missing some desired functionality (in which case tell me to implement that functionality ASAP!).

Thanks a lot for the explanation @andy-sweet, that's very helpful to know! Yeah, I will look to make it work with the layer.features then once I get to that part. My classifier anyway saves the relevant data internally, so I can just convert to a Pandas DataFrame when needed :)

> One reason we don't want to commit to a particular package's DataFrame is to try to support these kinds of use cases. For example, you might be able to use a [vaex DataFrame](https://vaex.io/docs/index.html) to lazily load data. That won't currently work with napari because we do always convert to a pandas DataFrame right now, but that is something I would be very open to changing in the future. So if that sounds promising, let me know, and we may be able to get some momentum behind it.

Fascinating! Yeah, we also aren't quite at the point where we actually need to access such large datasets lazily, though if things work out with scaling up, we would get there. I haven't heard of Vaex before, but would certainly be interested to see how it can be used in napari! Where can we start building momentum for this?

>If I understand the goal here, the crudest approach would be to prepend some unique string to the column names of the features to identify each image. By the sounds of your work, that table is going to be very wide though.
I have been considering whether we want to store feature measurements outside of any particular layer, which may be a more general purpose solution. So if that sounds promising, please push on that too.

My main goal here is: If a user opens different images and adds data from each, I want to be able to relate which data belonged to which image. See the output dataframe on the right in this image. Seems fairly easy with data on disk that I can just have a column with the path to the data, but not quite sure how I'd handle this when getting the data from `layer.features`.
![153728461-d685987d-e1a9-46ff-834b-073008252ccb](https://user-images.githubusercontent.com/18033446/153767333-ad81c1e1-48f2-4e6d-9bee-18cc8f156057.png)

The consideration here is that the user may have dozens, hundreds or thousands of images, each with linked data. The general solution links back to the Vaex discussion above again and for me the big question is: How should we store GBs of tabular data when we know we want to access different (small) subsets of it in napari for tasks like visualization, classification or such. If there is a direction for how large-scale tabular data could be stored in relation to large image datasets that could become a standard approach for handling this in napari, I'd be very interested in contributing to that (instead of just finding custom workarounds) and pushing for it where I can!
(Having csv files per image mostly works and has the big advantage of being fairly simple and easy to understand for users. But it's not really scaling that well and not very elegant to work with in napari)

**Comment by andy-sweet** [comment]
> I haven't heard of Vaex before, but would certainly be interested to see how it can be used in napari! Where can we start building momentum for this?

I think the best way is to create an issue in napari around making `Layer.features` support more than just pandas DataFrame (or dict like input for it), as it does now. This would include vaex, but should also take into account other pandas alternatives that could be useful (e.g. dask DataFrame).

> My main goal here is: If a user opens different images and adds data from each, I want to be able to relate which data belonged to which image.

Yeah, agreed that `Layer.features` does not solve that well right now for two reasons.
1. Requires all that data to be in memory. The likely solution is likely around supporting pandas alternatives that don't need to do that like vaex and dask (i.e. the thing above).
2. There's only one `Labels.features` and there isn't an `Image.features`. I was suggesting something like the following to abuse `Labels.features` 

```
   label  image1-feature1  image1-feature2  image2-feature1  image2-feature2
0      1              100              555              100               10
1      2             2200             1900             9001               50
```

but that's clearly not elegant.

The main advantage of using `Layer.features` is that it allows persisting and sharing tabular data between napari and plugins (e.g. so that we could visualize or export that tabular data as part of napari's core), and also between plugins. If you don't need either of those, then maybe your custom solution might be good enough? If you need to do some custom interchange between plugins, there's always the general purpose `Layer.metadata` which is just a plain dict.

> How should we store GBs of tabular data when we know we want to access different (small) subsets of it in napari for tasks like visualization, classification or such. If there is a direction for how large-scale tabular data could be stored in relation to large image datasets that could become a standard approach for handling this in napari, I'd be very interested in contributing to that (instead of just finding custom workarounds) and pushing for it where I can!

On the napari side, we'll almost definitely be targeting some subset of the existing solutions for this, rather than building our own (though maybe we'll wrap those to add some extra functionality). The packages that come to mind immediately are dask and arrow. I have not used those much in practice - but I'm sure there are people in the napari community that have. Another more general and possibly powerful solution that came up in a discussion recently is [TileDB](https://tiledb.com/embedded/), though I'm less aware of how much momentum that has in the scientific software community.

**Comment by jluethi** [comment]
Just a small sign of life here:
We're in the process of refactoring towards using `layer.features`. We have split the annotation workflow off from the classifier itself. In the 0.0.2 release, the annotator is available separately and writes annotations to a column in the `layer.features`. We'll tackle feature loading from there next :)

(see this PR for some of the details: https://github.com/fractal-napari-plugins-collection/napari-feature-classifier/pull/23)

**Comment by jluethi** [comment]
@haesleinhuepf We've started to use layer.features, but are running into a weird bug where the window keeps resizing. Have you run into this?
See https://github.com/napari/napari/issues/5617

**Comment by jluethi** [comment]
@haesleinhuepf Our refactor around using layer.features is now finished. The classifier and the annotator now both rely on the features in layer.features. Besides being generally more flexible & more stable, they should also work well with napari workflow outputs now. I'll still need to test this more myself as well, but feel free to open new issues if there are problems. This time, it won't take a year to close it 🙈
