### ISSUE TITLE
[Napari HUB cli] Metadata enhancement

### ISSUE THREAD

**Issue by seankmartin** [fractal-napari-plugins-collection/napari-feature-classifier#19]
Hi again,

I'm Sean, and I created this issue to complement #18.

While scanning your repository, I identified some metadata that are either missing, or misplaced in files that are considered as secondary or deprecated sources.

Since metadata sometimes is hard to fix automatically I created a list of what improvements you might want to look into to improve the overall quality of your [napari hub](https://napari-hub.org) listing:

* 'Source Code' entry was not found (scanned files: `pyproject.toml`, `setup.cfg`)
* 'Issue Submission Link' entry was not found (scanned files: `pyproject.toml`, `setup.cfg`)
* 'Support Channel Link' entry was not found (scanned files: `pyproject.toml`, `setup.cfg`)

* Screenshot/Video was found in `README.md`, but it is preferred to place this information in `.napari-hub\DESCRIPTION.md`
* Usage Overview was found in `README.md`, but it is preferred to place this information in `.napari-hub\DESCRIPTION.md`
* Intro Paragraph was found in `README.md`, but it is preferred to place this information in `.napari-hub\DESCRIPTION.md`
* Installation was found in `README.md`, but it is preferred to place this information in `.napari-hub\DESCRIPTION.md`

If you need, here are [more details about metadata and their locations](https://github.com/chanzuckerberg/napari-hub/wiki/Customizing-your-plugin%27s-listing).

As I mentioned in my PR, if some metadata is already present and I overlooked it, please feel free to contact me or [neuromusic](https://github.com/neuromusic) to tell us what could be improved!

Thank you for your help and feedback,

The napari hub and MetaCell teams.

**Comment by jluethi** [comment]
Hey @seankmartin 

Thanks a lot, will look into this PR. One thing I already noticed: The automatic creation seems to have had an issue with special characters in my name (and converted Lüthi to L\xFCthi).

Also, thanks for the suggestion list above. I'm a bit torn about adding too much of this information just to `.napari-hub\DESCRIPTION.md`, because I think it belongs into the README of the plugin => also visible this way on github & pypi. I'm also hesitant about duplicating it (maintenance). If I keep them just in `README.md`, will they still be displayed correctly or what are the benefits of putting this information (exclusively / a copy of it) in `.napari-hub\DESCRIPTION.md`?

**Comment by seankmartin** [comment]
Hi @jluethi,

I just wanted to let you know about the purpose of `.napari-hub\DESCRIPTION.md`, my apologies for the late reply!

The `.napari-hub/DESCRIPTION.md` file is an optional feature that allows you to create a napari hub specific version of your `README.md`. The idea is that you can write a new file (if you wish) with different information that targets a different audience than that on PyPI or GitHub. If you choose to just keep the `README.md` then the hub will display this no problem.

We also updated the handling of special characters in the tool so it should be clearer in the future :)

**Comment by jluethi** [comment]
Thanks again @seankmartin for the suggestions and explanations! I merged the PR with some minor adjustments and now added a few links to the setup.cfg as well (that was after the release, so will come to the hub with the next release) :)
